pipeline {
    agent {
        docker {
            image 'maven:3.9.6-sapmachine-17'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('build') {
            steps {
                echo 'Compiling worker app..'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running Unit Tests on worker app..'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }
    post {
        always {
            slackSend (channel: "#ci-cd", message: "Build completed: ${currentBuild.currentResult} ${env.JOB_NAME} ${env.BUILD_NUMBER}")
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}
